wandb:
    project: GNCDEs

epochs: 200
patience: 15
min_epochs: 20

seed: 1234
log_freq: 5
eval_freq: 5
logger_name: Temporal GRL
checkpoint_dir: .checkpoints/
checkpoint_name: stg_ncde

model:
    name: tgb_st_graph_neural_cde
    f_func:
        name: FinalTanhF
        hidden_dim: 8 # TODO: change back
        num_layers: 1
        data_embed_dim: 32
    g_func:
        name: STGraphVectorField
        hidden_dim: 8 # TODO: change back
        num_layers: 2
        node_embed_dim: 5
        num_nodes: 255
        cheb_k: 2
    use_initial: True
    interpolation: cubic
    method: Tsit5
    return_sequence: False
optimiser:
    name: adamw
    weight_decay: 1e-4
    gradient_clipping: True
    schedule:
        name: constant_schedule
        value: 1e-2
loss:
    name: MSE
    # name: L1
dataset:
    name: tgbn-trade
    window_size: 3
    stride: 3
    frequency: None
    split_ratio: [0.6, 0.2, 0.2]
    data_dir: datasets
    interpolation: cubic
    seed: 1234
