name: jax
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.11
    - pytorch
    - torchdiffeq
    - numpy
    - optax
    - pandas
    - jax
    - jaxtyping
    - lineax
    - equinox
    - diffrax
    - pyyaml
    - pydantic
    - networkx
    - matplotlib
    - seaborn
    - pytest
    - scikit-learn
    - scipy
    - tqdm
    - wandb
    - yaml
    - pip
    - pip:
          - exca
          - torch_geometric
          - torchcde
          - torchdata
          - py-tgb
