wandb:
    project: GNCDEs

epochs: 200
patience: 15
min_epochs: 20

checkpoint_dir: .checkpoints/
checkpoint_name: const
seed: 1234
log_freq: 25
eval_freq: 25
logger_name: Temporal GRL

model:
    name: tgb_graph_neural_ode
    vector_field:
        name: ConstVectorField
        hidden_dim: 32
        num_layers: 2
        data_embed_dim: 16
        use_control: False
        num_nodes: 1505
    hidden_dim: 32
    use_initial: True
    interpolation: cubic
    method: Tsit5
    return_sequence: False
optimiser:
    name: adamw
    weight_decay: 1e-4
    gradient_clipping: True
    schedule:
        name: constant_schedule
        value: 1e-2
loss:
    name: MSE
    # name: L1
dataset:
    name: tgbn-genre
    window_size: 10
    stride: 10
    frequency: weekly
    split_ratio: [0.6, 0.2, 0.2]
    data_dir: datasets
    interpolation: cubic
    seed: 1234
    normalise_features: True
