wandb:
    project: GNCDEs

epochs: 200
patience: 15
min_epochs: 20

checkpoint_dir: .checkpoints/
checkpoint_name: const
seed: 1234
log_freq: 25
eval_freq: 25
logger_name: Temporal GRL

model:
    name: pgt_graph_neural_ode
    vector_field:
        name: ConstVectorField
        hidden_dim: 32
        num_layers: 2
        data_embed_dim: 8
        use_control: False
        num_nodes: 129
    hidden_dim: 32
    data_dim: 8
    feature_dim: 1
    use_initial: True
    interpolation: cubic
    method: Tsit5
    return_sequence: False
optimiser:
    name: adamw
    weight_decay: 1e-4
    gradient_clipping: True
    schedule:
        name: constant_schedule
        value: 1e-2
loss:
    name: MSE
dataset:
    name: england-covid
    window_size: 5
    stride: 5
    split_ratio: [0.6, 0.2, 0.2]
    interpolation: cubic
    seed: 1234
