wandb:
    project: GNCDEs

epochs: 2000
patience: 200
min_epochs: 200

seed: 1234
log_freq: 25
eval_freq: 25
logger_name: Temporal GRL
checkpoint_dir: .checkpoints/
checkpoint_name: gnode_floor

model:
    name: graph_neural_ode
    vector_field:
        name: GNODEFloorVectorField
        hidden_dim: 16
        num_layers: 2
        use_control: False
    hidden_dim: 16
    use_initial: True
    interpolation: cubic
    method: Tsit5
    return_sequence: True
optimiser:
    name: adamw
    weight_decay: 1e-4
    gradient_clipping: True
    schedule:
        name: constant_schedule
        value: 1e-2
loss:
    name: MSE
    # name: L1
dataset:
    name: heat # choices=["heat", "gene", "mutualistic"], default="heat"
    batch_size: 4
    dynamic_graph: True # static graph or dynamic graph
    all_dynamic: True # Structural change for training phase only or for the whole sequence
    graph_type: grid # choices=["grid", "random", "power_law", "small_world", "community"], default="grid"
    split_ratio: [0.8, 0.2] # type=list, default=[0.8, 0.2], help="train and test ratio"
    num_nodes: 400
    final_time: 5.0 # terminal time
    time_tick: 100 # number of observations
    sampling_type: irregular # choices=["irregular", "equal"], default="irregular"
    method: Tsit5
    layout: community # choices=["community", "degree"], default="community"
    operator_type: norm_lap # choices=["lap", "norm_lap", "kipf", "norm_adj"], default="norm_lap",
    seed: 1234
    padding_mode: same
    cache_dir: .cache
    interpolation: cubic
    amp_range: [1.0, 1.0]
