wandb:
    project: GNCDEs

epochs: 2000
patience: 200
min_epochs: 200

seed: 1234
log_freq: 25
eval_freq: 25
logger_name: Temporal GRL
checkpoint_dir: .checkpoints/
checkpoint_name: perm_equiv_gncde

model:
    name: graph_neural_cde
    vector_field:
        name: PermEquivGraphVectorField
        hidden_dim: 16
        num_layers: 2
        use_control: False
    hidden_dim: 16
    use_initial: True
    interpolation: cubic
    method: Tsit5
    return_sequence: True
optimiser:
    name: adamw
    weight_decay: 1e-4
    gradient_clipping: True
    schedule:
        name: constant_schedule
        value: 10e-2
loss:
    name: MSE
dataset:
    name: heat
    batch_size: 4
    dynamic_graph: True
    all_dynamic: True
    graph_type: grid
    split_ratio: [0.8, 0.2]
    num_nodes: 400
    final_time: 5.0
    time_tick: 100
    sampling_type: irregular
    method: Tsit5
    layout: community
    operator_type: norm_lap
    seed: 1234
    padding_mode: same
    cache_dir: .cache
    interpolation: cubic
    amp_range: [1.0, 1.0]
